PREFIX adres: <https://data.vlaanderen.be/ns/adres#>
PREFIX locn: <http://www.w3.org/ns/locn#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?location adres:positie ?geom .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?location locn:geometry ?geom .
    FILTER NOT EXISTS { ?location adres:positie ?geom }
  }
}
